-- Auditoría / historial de acciones (solo Admin)
-- Ejecuta en Supabase SQL Editor.

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid not null,
  actor_name text,
  action text not null,
  target_type text,
  target_id uuid,
  target_name text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_action_idx on public.audit_logs (action);
create index if not exists audit_logs_actor_id_idx on public.audit_logs (actor_id);

alter table public.audit_logs enable row level security;

drop policy if exists "audit_logs_select_admin" on public.audit_logs;
create policy "audit_logs_select_admin"
on public.audit_logs
for select
to authenticated
using (public.is_admin(auth.uid()));

-- Insert lo hacemos desde backend con SERVICE_ROLE (bypass RLS)